### PR TITLE
Get-ModifiablePath: Add the parent directory of a .exe to $CandidatePaths

### PR DESCRIPTION
**Pull request by SAERXCIT**
Hey, thanks for this very useful tool :upside_down_face:

I edited the `Get-ModifiablePath` function in order to add a `.exe`'s parent directory to the `$CandidatePaths` variable.
This helps finding DLL hijacking vulnerabilities, as the .exe's directory is the first directory searched when searching for a DLL.

I had a case during an assignment where a program was installed to a non-standard directory, and thus did not inherit the restrictive ACLs of the standard `C:\Program Files` directory, instead inheriting default ACLs allowing non-privileged users to `AddFile` and `AddSubdirectory`. A service ran this program as a privileged user. This resulted in straightforward DLL hijacking privesc, which the current upstream version of `PrivescCheck` did not detect.

This PR allows the `Invoke-ServicesImagePermissionsCheck` function to detect such cases. If this check shows that a non-privileged user has the `AddFile` privilege on a directory containing a service binary, further `procmon` analysis of this binary is warranted :slightly_smiling_face:

This could also allow other similar checks to detect this kind of DLL hijacking vulnerabilities, such as `Invoke-ModifiableProgramsCheck`, `Invoke-ApplicationsOnStartupCheck`, `Invoke-ScheduledTasksImagePermissionsCheck`, though I have not tested these functions.

Cheers!

### CODE REVIEW

**Comment by itm4n** [comment]
Thank you very much for reporting this issue and proposing a solution.
You made a really good point there! 🙂 For some reason, I forgot to implement this. 

I think this change can be a bit more generic though.
If you consider a service that executes `C:\Vuln\service.exe`, and `service.exe` has proper file permissions. In this case `C:\Vuln\` would be reported as a finding, that's fine. However, if the service is configured with `C:\Vuln\service` as the ImagePath, which is a possibility, it would not be reported. Therefore, rather than testing if the extension is ".exe", we could simply check if it's a file.

I will need to review this very carefully. A change in this core function may have unintended side effects.

**Comment by itm4n** [comment]
It should be fixed now!

I updated `Get-ModifiablePath` with the following piece of code:
```powershell
if(Test-Path -Path $TempPath -ErrorAction SilentlyContinue) {

    $ResolvedPath = Resolve-Path -Path $TempPath | Select-Object -ExpandProperty Path
    $CandidatePaths += $ResolvedPath

    # If the path corresponds to a file, we want to check its parent directory as well. There are cases
    # where the target file is configured with secure permissions but a user can still add files in the
    # same folder. In such case, a DLL proxying attack is still possible.
    if ($(Get-Item -Path $ResolvedPath) -is [System.IO.FileInfo]) {
        $CandidatePaths += Get-FirstExistingParentFolder -Path $ResolvedPath
    }
} else {

    # If the path doesn't correspond to an existing file or directory, find the first existing parent
    # directory (if such directory exists) and add it to the list of candidate paths.
    $CandidatePaths += Get-FirstExistingParentFolder -Path $ResolvedPath
}
```

Here is the idea:
- If the target path is a file, I add the path and its parent directory to the list of candidate paths.
- If the target path is a directory, I just add it as is.
- If the target path doesn't exist at all, I try to get the first existing parent folder. This case is interesting if a service is configured with a phantom path for some reason (e.g.: the files were removed but the service itself still exists).

Previously, I already implemented a similar feature but I only checked whether the first parent folder existed. Therefore, I could still miss some vulnerable paths.

To solve this problem, I implemented a helper function that tries to get the first existing parent folder recursively.

```powershell
function Get-FirstExistingParentFolder {

    param(
        [string]$Path
    )

    try {
        $ParentPath = Split-Path $Path -Parent
        if($ParentPath -and $(Test-Path -Path $ParentPath -ErrorAction SilentlyContinue)) {
            Resolve-Path -Path $ParentPath | Select-Object -ExpandProperty "Path"
        } else {
            Get-FirstExistingParentFolder -Path $ParentPath
        }
    } catch {
        # because Split-Path doesn't handle -ErrorAction SilentlyContinue nicely
    }
}
```

Hope this makes sense. I think I might have introduced potential false positives with this method. But that's still better than missing vulnerable paths.

**Comment by itm4n** [comment]
This should be fixed now.

**Comment by SAERXCIT** [comment]
Hey!

It turns out the following fix does not seem to be correct. The `$ResolvedPath` variable does not exist in the `else` bloc: 

> ```powershell
> if(Test-Path -Path $TempPath -ErrorAction SilentlyContinue) {
> 
>     $ResolvedPath = Resolve-Path -Path $TempPath | Select-Object -ExpandProperty Path
>     $CandidatePaths += $ResolvedPath
> 
>     # If the path corresponds to a file, we want to check its parent directory as well. There are cases
>     # where the target file is configured with secure permissions but a user can still add files in the
>     # same folder. In such case, a DLL proxying attack is still possible.
>     if ($(Get-Item -Path $ResolvedPath) -is [System.IO.FileInfo]) {
>         $CandidatePaths += Get-FirstExistingParentFolder -Path $ResolvedPath
>     }
> } else {
> 
>     # If the path doesn't correspond to an existing file or directory, find the first existing parent
>     # directory (if such directory exists) and add it to the list of candidate paths.
>     $CandidatePaths += Get-FirstExistingParentFolder -Path $ResolvedPath
> }
> ```

As such, the parent directory of a non-existing file will not be added to the `$CandidatePaths`, leading to false negatives when a non-existing `.exe` is within a user-writable directory.

Replacing `$ResolvedPath` with `$TempPath` in both `else` blocs (lines 1577 and 1617) seems to fix this issue, but I don't know about potential side effects.

Cheers!

**Comment by itm4n** [comment]
Yup, you're completely right.
I'm refactoring the entire code right now, this will be fixed in the next commit.
Thanks again for your help.
I wonder how I could possibly miss this stupid mistake. :thinking:

**Pull request closed without merging**
